services:
  app:
    build: .
    container_name: pokemon_app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/pokemon_db
      - APP_PORT=3000
    volumes:
      - .:/usr/src/app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
